#
# $Id$
#
# $Log$
# Revision 1.4  1994/11/01 22:43:26  vong
# Overwritten the 1.4.6 makefile
#
# Revision 1.2  1994/10/05  18:56:55  jba
# Initial versions
#
#

EPICS=../../../..

include $(EPICS)/config/CONFIG_EXTENSIONS

include $(EPICS)/config/RULES_ARCHS

