# Makefile for medm/xc (Widgets)

ifeq ($(HOST_ARCH),WIN32)

TOP=../../..

include $(TOP)/config/CONFIG_EXTENSIONS

include $(TOP)/config/RULES_ARCHS

else

EPICS=../../../..

include $(EPICS)/config/CONFIG_EXTENSIONS

include $(EPICS)/config/RULES_ARCHS

endif
