
widgetDM_4	-Adobe-Helvetica-Medium-R-Normal--8-80-75-75-P-46-ISO8859-1
widgetDM_6	-Adobe-Helvetica-Medium-R-Normal--8-80-75-75-P-46-ISO8859-1
widgetDM_8	-Adobe-Helvetica-Medium-R-Normal--8-80-75-75-P-46-ISO8859-1
widgetDM_10	-Adobe-Helvetica-Medium-R-Normal--10-100-75-75-P-56-ISO8859-1
widgetDM_12	-Adobe-Helvetica-Medium-R-Normal--12-120-75-75-P-67-ISO8859-1
widgetDM_14	-Adobe-Helvetica-Medium-R-Normal--14-140-75-75-P-77-ISO8859-1
widgetDM_16	-Adobe-Helvetica-Medium-R-Normal--14-140-75-75-P-77-ISO8859-1
widgetDM_18	-Adobe-Helvetica-Medium-R-Normal--18-180-75-75-P-98-ISO8859-1
widgetDM_20	-Adobe-Helvetica-Medium-R-Normal--18-180-75-75-P-98-ISO8859-1
widgetDM_22	-Adobe-Helvetica-Medium-R-Normal--24-240-75-75-P-130-ISO8859-1
widgetDM_24	-Adobe-Helvetica-Medium-R-Normal--24-240-75-75-P-130-ISO8859-1
widgetDM_30	-Bitstream-Charter-Bold-R-Normal--25-240-75-75-P-157-ISO8859-1
widgetDM_36	-Bitstream-Terminal-Medium-R-Normal--36-360-75-75-C-220-ISO8859-1
widgetDM_40	-Bitstream-Terminal-Medium-R-Normal--36-360-75-75-C-220-ISO8859-1
widgetDM_48	-Bitstream-Terminal-Medium-R-Normal--36-360-75-75-C-220-ISO8859-1
widgetDM_60	-Bitstream-Terminal-Medium-R-Normal--36-360-75-75-C-220-ISO8859-1
