#
# $Id$
#
# $Log$
# Revision 1.4  1994/11/02 18:40:12  vong
# to add the the extension library path
#
# Revision 1.2  1994/10/05  18:56:50  jba
# Initial versions
#
#

EPICS=../../../..

include $(EPICS)/config/CONFIG_EXTENSIONS

include $(EPICS)/config/RULES_ARCHS

