ADD_ON = ../../../..

include $(ADD_ON)/src/config/CONFIG


USR_CFLAGS = $(MOTIF_CFLAGS) $(X11_CFLAGS)

SRCS = dsimple.c pUtils.c ps_utils.c utilPrint.c xwd.c xwd2ps.c

OBJS = dsimple.o pUtils.o ps_utils.o utilPrint.o xwd.o xwd2ps.o

LIBNAME = libPrintUtils.a

include $(ADD_ON)/src/config/RULES

